[package]
name = "advent-2020"
version = "0.1.0"
authors = ["Nick Pearson"]
edition = "2018"

[dependencies]
regex = "1"
lazy_static = "1.4.0"
threadpool = "1.8.1"
num_cpus = "1.13.0"
joinery = "2.0.0"

[[bin]]
name = "1"
path = "src/1/main.rs"

[[bin]]
name = "2"
path = "src/2/main.rs"

[[bin]]
name = "3"
path = "src/3/main.rs"

[[bin]]
name = "4"
path = "src/4/main.rs"

[[bin]]
name = "5"
path = "src/5/main.rs"

[[bin]]
name = "6"
path = "src/6/main.rs"

[[bin]]
name = "7"
path = "src/7/main.rs"

[[bin]]
name = "8"
path = "src/8/main.rs"

[[bin]]
name = "9"
path = "src/9/main.rs"

[[bin]]
name = "10"
path = "src/10/main.rs"

[[bin]]
name = "11"
path = "src/11/main.rs"

[[bin]]
name = "12"
path = "src/12/main.rs"

[[bin]]
name = "13"
path = "src/13/main.rs"

[[bin]]
name = "14"
path = "src/14/main.rs"

[[bin]]
name = "15"
path = "src/15/main.rs"

[[bin]]
name = "16"
path = "src/16/main.rs"

[[bin]]
name = "17"
path = "src/17/main.rs"

[[bin]]
name = "18"
path = "src/18/main.rs"

[[bin]]
name = "19"
path = "src/19/main.rs"

[[bin]]
name = "20"
path = "src/20/main.rs"

[[bin]]
name = "21"
path = "src/21/main.rs"

[[bin]]
name = "22"
path = "src/22/main.rs"

[[bin]]
name = "23"
path = "src/23/main.rs"

[[bin]]
name = "24"
path = "src/24/main.rs"